version: "3.8"

services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}

  app:
    build: .
    image: ${DOCKER_IMAGE:-YOUR_DOCKERHUB_USER/placement-cell:latest}
    depends_on:
      - mongo
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env
    restart: unless-stopped

volumes:
  mongo-data:
